services:
  localstack-dev:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-dev}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume-dev}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  localstack-uat:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-uat}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4567:4566"
      - "127.0.0.1:4610-4659:4510-4559"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume-uat}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
